---
options:
  merge-default-rules: false
  # formatter: stylish
  formatter: stylish
  # output-file: 'sass-lint.html'
rules:
  extends-before-declarations: 1
  extends-before-mixins: 1
  leading-zero: 1
  mixins-before-declarations: 1
  no-color-keywords: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    -
      extra-properties:
        - font-smooth
  no-trailing-zero: 1
  # no-transition-all: 1
  one-declaration-per-line: 1
  property-sort-order: 1
  quotes: 1
  single-line-per-selector: 1
  space-after-colon: 1
  space-after-comma: 1
  space-before-brace: 1
  url-quotes: 1
  zero-unit: 1
